services:
  private-relay:
    image: ghcr.io/nogringo/nostr-private-relay:main
    container_name: nostr-private-relay
    ports:
      - "${PORT:-3334}:3334"
    volumes:
      - data:/app/data
    env_file:
      - .env
    restart: unless-stopped

volumes:
  data:
